export const FETCH_FLIGHTS = 'FETCH_FLIGHTS';
export const FETCH_FLIGHTS_SUCCESS = 'FETCH_FLIGHTS_SUCCESS';
export const GET_CAROUSEL_IMAGES = 'GET_CAROUSEL_IMAGES';
export const SET_FAVORITES_COUNT = 'SET_FAVORITES_COUNT'